config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  namespace :blog do
    resources :sites
    resources :site_configs, only: [:create, :update]
  end

end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/blog/post.rb
class Blog::Post < ActiveRecord::Base
  include Elasticsearch::Model

  MAX_POST_TAGS_LENGTH = 5

  belongs_to :site, foreign_key: :blog_site_id
  has_many :post_tags, foreign_key: :blog_post_id
  has_many :tags, through: :post_tags

  validates :blog_site_id, presence: true
  validates :permalink, presence: true, uniqueness: true, length: {maximum: 64}
  validates :title, presence: true, length: {maximum: 128}
  validates :content, presence: true
  validates :post_tags, length: {maximum: MAX_POST_TAGS_LENGTH}
end

app/models/blog/post_tag.rb
class Blog::PostTag < ActiveRecord::Base
  belongs_to :post, foreign_key: :blog_post_id
  belongs_to :tag, foreign_key: :blog_tag_id

  validates :blog_post_id, presence: true
  validates :blog_tag_id, presence: true, uniqueness: {scope: :blog_post_id}
end

app/models/blog/site.rb
class Blog::Site < ActiveRecord::Base
  belongs_to :user
  has_one :site_config, foreign_key: :blog_site_id
  has_many :posts, foreign_key: :blog_site_id

  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 128}, uniqueness: {scope: :user_id}
  validates :description, presence: true
  validates_with Blog::SiteDescriptionSignificanceValidator

  before_save Blog::SiteLanguageEstimator.new(:language)

  def rating
    @rating ||= Blog::SiteRating.from_description(description)
  end
end

app/models/blog/site_config.rb
class Blog::SiteConfig < ActiveRecord::Base
  belongs_to :site, foreign_key: :blog_site_id

  validates :blog_site_id, presence: true, uniqueness: true
  validates :redirect_to, length: {maximum: 255}
end

app/models/blog/tag.rb
class Blog::Tag < ActiveRecord::Base
  has_many :post_tags, foreign_key: :blog_tag_id

  validates :name, presence: true, uniqueness: true, length: {maximum: 255}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def pundit_auth
    authorize(pundit_record)
  rescue Pundit::NotDefinedError
    authorize(:application)
  end

  def pundit_record
    controller_path.to_sym
  end
end

app/controllers/blog/site_configs_controller.rb
# app/controllers/blog/site_configs_controller.rb
class Blog::SiteConfigsController < ApplicationController
  before_action :set_site_config, only: [:update]

  def create
    @site_config =
      Blog::SiteConfig.new(site_config_params)
    if @site_config.save
      render json: @site_config
    else
      render json: {message: 'Save Failure'}, status: 400
    end
  end

  def update
    if @site_config.update(site_config_params)
      render json: @site_config
    else
      render json: {message: 'Update Failure'}, status: 400
    end
  end

  private

  def set_site_config
    @site_config = Blog::SiteConfig.find(params[:id])
  end

  def site_config_params
    params.require(:site_config).permit(:site_id, :redirect_to)
  end
end

app/controllers/blog/sites_controller.rb
class Blog::SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_action :pundit_auth
  before_action :verify_authorized

  respond_to :html, :xml, :json

  def index
    @sites = policy_scope(Blog::Site)
  end

  def show
    @site_stats = Blog::SiteStatsGenerator.new(@site).generate
  end

  def new
    @site_form = Blog::SiteForm.new
  end

  def edit
    @site_form = Blog::SiteForm.new(site: @site)
  end

  def create
    logging_form = Blog::SiteFormLogger.new(Blog::SiteForm.new(site_params))
    @site_form = logging_form.site_form

    if logging_form.save(current_user)
      @site = @site_form.site
      render :show
    else
      render :new
    end
  end

  def update
    @site.update(site_params)
    respond_with(@site)
  end

  def destroy
    @site.destroy
    respond_with(@site)
  end

  private

  def set_site
    @site = Blog::Site.find(params[:id])
  end

  def site_params
    params.
      require(:blog_site_form).
      permit(:title, :description).
      merge(user: current_user)
  end

  def pundit_record
    @site || controller_path.to_sym
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog/sites_helper.rb
module Blog::SitesHelper
end

app/views/blog/sites/_form.html.slim
= form_for @site_form, url: polymorphic_path(@site_form.site) do |f|
  - if @site_form.errors.any?
    #error_explanation
      h2 = "#{pluralize(@site_form.errors.count, "error")} prohibited this blog_site from being saved:"
      ul
        - @site_form.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit 'Save'

app/views/blog/sites/edit.html.slim
h1 Editing blog_site

== render 'form'

= link_to 'Show', @site
'|
= link_to 'Back', blog_sites_path

app/views/blog/sites/index.html.slim
/ app/views/blog/sites/index.html.slim
- @body_id = 'blog-sites-index-page'

h1 Listing blog_sites

table
  thead
    tr
      th Title
      th Description
      th Redirect To
      th
      th
      th

  tbody
    - @sites.each do |blog_site|
      tr.blog-site id="blog-site-#{blog_site.id}" data-id=blog_site.id
        td = blog_site.title
        td = blog_site.description
        td.blog-site-config data-id=(blog_site.config.id if blog_site.config)
          - show_visible = !!blog_site.config
          span.blog-site-config-show style=('display: none;' unless show_visible)
            p.redirect-to-show data-blog-site-id=blog_site.id #{blog_site.config.try(:redirect_to)}
            button.redirect-to-edit data-blog-site-id=blog_site.id 編集
          - edit_visible = !blog_site.config
          span.blog-site-config-edit style=('display: none;' unless edit_visible)
            input.redirect-to-input value=blog_site.config.try(:redirect_to)
            button.redirect-to-save data-blog-site-id=blog_site.id 保存
        td = link_to 'Show', blog_site
        td = link_to 'Edit', edit_blog_site_path(blog_site)
        td = link_to 'Destroy', blog_site, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Site', new_blog_site_path

app/views/blog/sites/new.html.slim
h1 New blog_site

== render 'form'

= link_to 'Back', blog_sites_path

app/views/blog/sites/show.html.slim
- @site = Blog::SitePresenter.new(@site, self)
p#notice = notice

p
  strong Title:
  = @site.title
p
  strong Description:
  = @site.description
p
  strong Updated at:
  = @site.updated_at

p
  strong Stats:
  = @site_stats

= link_to 'Edit', edit_blog_site_path(@site.object)
'|
= link_to 'Back', blog_sites_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsSandboxEnogineerCom
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body id=@body_id class=@body_class
    = render('/header')
    = yield